var bankName;
bankName = "SBI Bank";
console.log("bank name is", bankName);
console.log("type of variable is:", typeof bankName);
var marks;
marks = "90%";
console.log("the marks is :", marks);
console.log("type of variables marks:", typeof marks);
var isWork;
var isWork1 = false;
console.log("type variable isworking:", isWork);
console.log("are you working :", isWork1);
var totalCount;
totalCount = "Hundred and seven";
console.log("total count is:", totalCount);
console.log("1> type of variable is:", typeof totalCount);
var totalCount;
totalCount = 107;
console.log("total count is:", totalCount);
console.log("2> type of variable is:", typeof totalCount);
