console.log("******* implicit conversion to string ******************");
  
 var result= '3' + 2;
 console.log("the given string is: '3'+2");
 var result = (result);
 console.log(`the result is: ${result}`);
 console.log(`Bec first valu is string and second value is number and conversion method + is used rsult is`);
 console.log("***************************  second **********************");
 var result= '3'+true;
 console.log("the given string is: '3'+true");
 var result = (result);
 console.log(`the result is :${result}`);
 console.log("bec first value string and second valu boolean conversion + is used ");
 console.log("*************************** third*******************");
   
   var result= '3'+ undefined;
   console.log("the given string is: '3'+undefined");
   var result=(result);
   console.log(`the result is:${result}`);
   console.log("bec the first valu is string and second valu undefined conversion + is used");
   console.log("********************** fourth ********************");
   var result= '3'+ null;
   console.log("the given string is: '3'+null");
   var result=(result);
   console.log(` the result is:${result}`);
   console.log("first valu is string and second valu null conversion + is used");
   console.log("************ implicit boolean to number ************************");
   var result='4'-true;
   console.log("boolean value true consider 1, 4-1=3");
   console.log( `result is`,result);
   console.log("***************************************************************");
   var result='4'+true;
   console.log("boolean value consider true=1,false=0 4+1=5");
   console.log(` result is :`,result);
   console.log("*****************************************************************");
   var result='4'+false;
   console.log("boolean value true=1,false=0 4+0=4");
   console.log(`result is :`,result);
   console.log("***************** Implicit string conversion to number *****************");
    
         var result='4' -'2';
          //console.log(result);
          console.log("the result is 4-2 =2",result);
          console.log("******************************************************************");
          var result='4' -2;
          //console.log(result);
          console.log("the result is 4-2 =2",result);
          console.log("*******************************************************************");
          var result='4'*2;
          //console.log(result);
          console.log("the result is 4*2 =8",result);
          console.log("*********************************************************************");
          var result='4'/2;
          //console.log(result);
          console.log("the result is 4/2 =2",result);
          console.log("*********************************************************************");